### ISSUE TITLE
Can't import/stream datas

### ISSUE THREAD

**Issue by OuesFa** [elasticsearch/elasticsearch-river-twitter#86]
Hi,
I'm on ES 1.4.1 / Plugin river-twitter 2.4.1
I use kibana 4 to see my datas.
I'm behind a proxy, so that's my PUT request:
![capture11](https://cloud.githubusercontent.com/assets/10348298/5683640/c534ce58-9829-11e4-95cf-1681aae9a793.PNG)
![capture00](https://cloud.githubusercontent.com/assets/10348298/5683587/5e96d196-9829-11e4-97bf-050752302b80.PNG)

So the index is created but in can't see any data on kibana, no datas in my cluster with the index _river.
Sorry if it's a dumb request.
Any help please ?

**Comment by dadoonet** [comment]
Nothing really obvious. Just wondering if you could try to reduce `bulk_size` to 1 to see if it's an issue with bulk settings?

What gives a `GET /tweets/_search` BTW?

**Comment by OuesFa** [comment]
bulk_size reduced to 1.
The result of GET request : 
![capture12](https://cloud.githubusercontent.com/assets/10348298/5684099/afed0f7a-982d-11e4-9009-a088cfc8329d.PNG)

**Comment by dadoonet** [comment]
Nothing in logs? Could you modify logs level to TRACE for `river.twitter` so we can get more details?

**Comment by OuesFa** [comment]
This is what i found without setting log level to TRACE:
[2015-01-09 19:32:20,114][WARN ][river.twitter            ] [Warwolves] [twitter][mes_tweets] stream failure, restarting stream...
401:Authentication credentials (https://dev.twitter.com/pages/auth) were missing or incorrect. Ensure that you have set valid consumer key/secret, access token/secret, and the system clock is in sync.
<html>\n<head>\n<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>\n<title>Error 401 Unauthorized</title>
</head>
<body>
<h2>HTTP ERROR: 401</h2>
<p>Problem accessing '/1.1/statuses/filter.json'. Reason:
<pre>    Unauthorized</pre>


I checked my credentials again and my config seems to be good, i tried to re-generate Keys and Access tokens, same result.
I've to set log level to TRACE to have more details may be.



TwitterException{exceptionCode=[115b1ded-51159d25], statusCode=401, message=null, code=-1, retryAfter=-1, rateLimitStatus=null, version=4.0.2}
	at twitter4j.HttpClientImpl.handleRequest(HttpClientImpl.java:163)
	at twitter4j.HttpClientBase.request(HttpClientBase.java:53)
	at twitter4j.HttpClientBase.post(HttpClientBase.java:82)
	at twitter4j.TwitterStreamImpl.getFilterStream(TwitterStreamImpl.java:306)
	at twitter4j.TwitterStreamImpl$7.getStream(TwitterStreamImpl.java:287)
	at twitter4j.TwitterStreamImpl$TwitterStreamConsumer.run(TwitterStreamImpl.java:488)
[2015-01-11 00:00:00,061][INFO ][twitter4j.TwitterStreamImpl] Waiting for 10000 milliseconds
[2015-01-11 00:00:00,061][INFO ][river.twitter            ] [Warwolves] [twitter][mes_tweets] starting filter twitter stream
[2015-01-11 00:00:00,061][INFO ][twitter4j.TwitterStreamImpl] Establishing connection.
[2015-01-11 00:00:00,499][INFO ][twitter4j.TwitterStreamImpl] 401:Authentication credentials (https://dev.twitter.com/pages/auth) were missing or incorrect. Ensure that you have set valid consumer key/secret, access token/secret, and the system clock is in sync.
<html>\n<head>\n<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>\n<title>Error 401 Unauthorized</title>
</head>

**Comment by dadoonet** [comment]
Could you run the same test from your home or wherever you don't have a proxy and make sure that your credentials are OK?

I believe your twitter credentials are incorrect here.

Closing as I don't see it as an issue but feel free to reopen if you feel it's an issue.
