### ISSUE TITLE
[Test] ThreadLeak detection while running tests

### ISSUE THREAD

**Issue by dadoonet** [elasticsearch/elasticsearch-river-twitter#99]
When we run tests, the test framework detects Thread leaks:

```
Throwable #2: com.carrotsearch.randomizedtesting.ThreadLeakError: There are still zombie threads that couldn't be terminated:
   >    1) Thread[id=317, name=Twitter4J Async Dispatcher[0], state=WAITING, group=TGRP-TwitterIntegrationTest]
   >         at sun.misc.Unsafe.park(Native Method)
   >         at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
   >         at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
   >         at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
   >         at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1068)
   >         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
   >         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
   >         at java.lang.Thread.run(Thread.java:745)
   >    at __randomizedtesting.SeedInfo.seed([7EBEF43EC89FBD41]:0)
```

It sounds like it's caused by Twitter4J which run one Thread `Twitter4J Async Dispatcher` and can not stop it quickly enough.

**Comment by dadoonet** [comment]
It sounds like we still have thread leaks:

```
2> Feb 19, 2015 11:26:33 AM com.carrotsearch.randomizedtesting.ThreadLeakControl checkThreadLeaks
  2> WARNING: Will linger awaiting termination of 1 leaked thread(s).
  2> Feb 19, 2015 11:26:38 AM com.carrotsearch.randomizedtesting.ThreadLeakControl checkThreadLeaks
  2> SEVERE: 1 thread leaked from SUITE scope at org.elasticsearch.river.twitter.test.TwitterIntegrationTest: 
  2>    1) Thread[id=206, name=Twitter4J Async Dispatcher[0], state=WAITING, group=TGRP-TwitterIntegrationTest]
  2>         at sun.misc.Unsafe.park(Native Method)
  2>         at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
  2>         at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
  2>         at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
  2>         at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1068)
  2>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
  2>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
  2>         at java.lang.Thread.run(Thread.java:745)
  2> Feb 19, 2015 11:26:38 AM com.carrotsearch.randomizedtesting.ThreadLeakControl tryToInterruptAll
  2> INFO: Starting to interrupt leaked threads:
  2>    1) Thread[id=206, name=Twitter4J Async Dispatcher[0], state=WAITING, group=TGRP-TwitterIntegrationTest]
  2> Feb 19, 2015 11:26:41 AM com.carrotsearch.randomizedtesting.ThreadLeakControl tryToInterruptAll
  2> SEVERE: There are still zombie threads that couldn't be terminated:
  2>    1) Thread[id=206, name=Twitter4J Async Dispatcher[0], state=WAITING, group=TGRP-TwitterIntegrationTest]
  2>         at sun.misc.Unsafe.park(Native Method)
  2>         at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
  2>         at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
  2>         at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
  2>         at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1068)
  2>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
  2>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
  2>         at java.lang.Thread.run(Thread.java:745)
```

It might requires more time for Twitter4J to close?
